# Generated by Django 2.2.5 on 2020-01-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ementa', models.CharField(max_length=280, verbose_name='Ementa')),
                ('descritivo', models.TextField(max_length=500, verbose_name='Descritivo')),
                ('justificativa', models.CharField(max_length=280, verbose_name='Ementa')),
                ('apoiador', models.ManyToManyField(to='accounts.UserProfile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugestoes.Status')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugestoes.Tema')),
            ],
        ),
    ]
