# Generated by Django 2.2.5 on 2020-02-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sugestoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='concordo',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='justificativa',
            field=models.CharField(max_length=280, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sugestoes.Status'),
        ),
    ]
