# Generated by Django 3.0.2 on 2020-08-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugestoes', '0002_auto_20200203_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(default='Titulo', max_length=140, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
